# Generated by Django 5.1 on 2024-08-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_rename_news_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
